[package]
name = "pySpinW"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version="0.24.2", features=["num-complex"]}
numpy = {version="0.24.0", features=["nalgebra"]}
nalgebra = "0.33.2" 
num-complex = "0.4.6"
rayon = "1.10.0"
