[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "pySpinW"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "pyspinw.rust"

[tool.setuptools.dynamic]
version = {attr = "pyspinw.__version__"}

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["D1",  # undocumented objects 
          "D2",  # docstring formating w.r.t. whitespace
          "E",  # pycodestyle errors
          "PL",  # pylint
          "W",  # pycodestyle warnings
          ]

ignore = ["D107",  # undocumented __init__
          "D203",  # 1 blank line before class docstring
          "D210",  # whitespace surrounding docstring text
          "D213",  # multi-line summary starts at second line
          "PLR",  # pylint refactor suggestions
          ]
