name: Lint

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up python paths (POSIX)
      run: |
        export PYTHONPATH=pyspinw
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff 
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Analysing the code with ruff 
      run: |
        ruff check pyspinw/ 
