name: Build and Publish

on:
  push:
    tags:
      - 'v*'   # Trigger only on version tags
jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CIBW_SKIP: "*32"
      #CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Make wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-windows
          path: wheelhouse

  build-macos:
    runs-on: macos-latest
    env:
      CIBW_ARCHS_MACOS: "x86_64 arm64"
      MACOSX_DEPLOYMENT_TARGET: "10.12"
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Rust targets (macOS)
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Set up python
        uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Make wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-macos
          path: wheelhouse

  build-linux:
    runs-on: ubuntu-latest
    env:
      CIBW_BEFORE_ALL_LINUX: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        rustup target add x86_64-unknown-linux-musl
      CIBW_ENVIRONMENT: PATH="$HOME/.cargo/bin:$PATH"
      #CIBW_ARCHS_LINUX: "x86_64 aarch64"

    steps:

      - name: Get repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Make wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-linux
          path: wheelhouse

  publish:
    needs:
      - build-windows
      - build-macos
      - build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: wheelhouse

      - name: Flatten wheelhouse
        run: |
          mkdir -p wheelhouse-flattened
          find wheelhouse -name "*.whl" -exec mv {} wheelhouse-flattened/ \;

      - name: Install twine
        run: pip install twine


      - name: Select the target repository
        id: repo
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ "$TAG_NAME" == *test ]]; then
            echo "repository=testpypi" >> $GITHUB_OUTPUT
          else
            echo "repository=pypi" >> $GITHUB_OUTPUT
          fi

      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ steps.repo.outputs.repository == 'testpypi' && secrets.TEST_PYPI_API_TOKEN || secrets.PYPI_API_TOKEN }}
        run: |
          if [ "${{ steps.repo.outputs.repository }}" = "testpypi" ]; then
            twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse-flattened/*.whl
          else
            twine upload wheelhouse-flattened/*.whl
          fi